<?xml version="1.0" encoding="UTF-8"?>
<saml2p:Response
  Destination="http://1.lvh.me/users/auth/suomifi/callback"
  ID="_32dec76e372bed25b053f0ab87625925"
  InResponseTo="_821e268b-5a13-4c7b-b3de-4f8cd9b3e525"
  IssueInstant="2019-08-13T17:23:01.827Z"
  Version="2.0"
  xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol">
  <saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">https://testi.apro.tunnistus.fi/idp1</saml2:Issuer>
  <saml2p:Status>
    <saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Requester">
      <saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:AuthnFailed"/>
    </saml2p:StatusCode>
    <saml2p:StatusMessage>An error occurred.</saml2p:StatusMessage>
  </saml2p:Status>
</saml2p:Response>
